pub_hdrs = {hxx ixx txx}{**}

./: $pub_hdrs

hxx{export}@./: cxx.importable = false

# Install into the asio/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/asio/
  install.subdirs = true
}
